# Telegram bot configuration
bot:
  token: "token"

# Openweather configuration
openweather:
  apptoken: "token"

MongoProperties:
  mongoHost: "localhost"
  mongoPort: "27017"
  mongoDatabase: "test"